### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by redblueyellow** [mynyml/harmony#1]
I'll sum it up with this:

LoadError: no such file to load -- envjs

ERROR:  Error installing envjs:
    envjs requires johnson (>= 2.0.0.pre1, runtime)

ERROR:  Error installing harmony:
    harmony requires johnson (= 2.0.0.pre0, runtime)

**Comment by redblueyellow** [comment]
Oh, and:

Gem::LoadError: can't activate johnson (>= 2.0.0.pre1, runtime) for ["envjs-0.1.2"], already activated johnson-2.0.0.pre0 for ["harmony-0.5.1"]

**Comment by qhoxie** [comment]
You either need to install a previous version of envjs to match pre0 for johnson, or you can uninstall pre0 and install pre1.  Both should work.  mynyml is working on a version bump on the deps, I believe.

**Comment by redblueyellow** [comment]
I downloaded the source, changed the version requirement to 2.0.0.pre1, built my own gem, and it seems to work fine with envjs 0.1.2. :)

**Comment by qhoxie** [comment]
The johnson version is now bumped in master.  This should work with the bundled envjs.
