### ISSUE TITLE
TypeError: malformed UTF-8 character sequence at offset 284

### ISSUE THREAD

**Issue by superp** [mynyml/harmony#6]
I get error:
 WARNIING:  [Sun Apr 04 2010 00:18:27 GMT+0300 (MSK)] {ENVJS} Exception while processing XHR: TypeError: malformed UTF-8 character sequence at offset 284
 WARNIING:  [Sun Apr 04 2010 00:18:27 GMT+0300 (MSK)] {ENVJS} Exception while loading window: TypeError: malformed UTF-8 character sequence at offset 284
/usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:362 [JavaScript]: malformed UTF-8 character sequence at offset 284 (Johnson::Error)
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:2425:in `makeRequest' [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:2437 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:3729 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:1140 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:2646 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:95 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:2655 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:6 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/runtime.rb:49:in`evaluate_compiled_script'
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/runtime.rb:53:in `evaluate'
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/runtime.rb:189:in`extended'
    from /usr/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in `call'
    from /usr/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in`**send**'
    from /usr/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in `send_with_possible_block'
    from /usr/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/runtime.rb:49:in`evaluate_compiled_script_without_clearing_traps'
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:591 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:1111 [JavaScript]
    from none:1 [JavaScript]
    from /usr/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/runtime.rb:49:in `evaluate_compiled_script'
    from /usr/lib/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/runtime.rb:53:in`evaluate'
    from /usr/lib/ruby/gems/1.8/gems/harmony-0.5.5/lib/harmony/page.rb:25:in `from_uri'
    from /usr/lib/ruby/gems/1.8/gems/harmony-0.5.5/lib/harmony/page.rb:30:in`from_document'
    from /usr/lib/ruby/gems/1.8/gems/harmony-0.5.5/lib/harmony/page.rb:65:in `initialize'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:208:in`new'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:208:in `decode'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:154:in`send_invite'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:150:in `each'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:150:in`send_invite'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:144:in `times'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:144:in`send_invite'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:131:in `start'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:118:in`each'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:118:in `start'
    from /var/www/autologo/auto.code/tools/vkontakte.rb:240

What does it mean?

**Comment by mynyml** [comment]
It means there's a "malformed UTF-8 character sequence at offset 284" :)

What code do you have in vkontakte.rb? And which version of harmony/johnson are you running?

**Comment by superp** [comment]
problem solved.
was different encoding text
tnx :)
