### ISSUE TITLE
jquery raises exception when loading

### ISSUE THREAD

**Issue by wilkerlucio** [mynyml/harmony#9]
Hi, im trying to use Harmony with a Sinatra app using jQuery, in my specs I did:

  context "javascript testing" do
    before :each do
      get '/'

```
  @page = Harmony::Page.new(last_response.body)
  @page.load("../public/javascripts/jquery-1.4.2.js")
end

it "should include jquery" do
  @page.execute_js("jQuery").inspect
end
```

  end

but in the line that I load the jQuery (in before filter) it raises an exception:

1)
TypeError in 'Layout Slicer javascript testing should include jquery'
can't convert nil into String
/Users/wilkersilva/.bundle/ruby/1.8/gems/envjs-0.3.1/lib/envjs/runtime.rb:186:in `extended'
/Users/wilkersilva/.bundle/ruby/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in`call'
/Users/wilkersilva/.bundle/ruby/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in `__send__'
/Users/wilkersilva/.bundle/ruby/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in`send_with_possible_block'
/Users/wilkersilva/.bundle/ruby/1.8/gems/johnson-2.0.0.pre3/lib/johnson/ruby_land_proxy.rb:110:in `call_function_property'
/Users/wilkersilva/.bundle/ruby/1.8/gems/envjs-0.3.1/lib/envjs/env.js:105 [JavaScript]
/Users/wilkersilva/.bundle/ruby/1.8/gems/johnson-2.0.0.pre3/lib/johnson/ruby_land_proxy.rb:110:in`method_missing'
/Users/wilkersilva/.bundle/ruby/1.8/gems/harmony-0.5.5/lib/harmony/page.rb:76:in `load'
/Users/wilkersilva/.bundle/ruby/1.8/gems/harmony-0.5.5/lib/harmony/page.rb:75:in`each'
/Users/wilkersilva/.bundle/ruby/1.8/gems/harmony-0.5.5/lib/harmony/page.rb:75:in `load'
/Users/wilkersilva/Development/layout_slicer/spec/layout_slicer_spec.rb:21:

**Comment by mynyml** [comment]
The only way I can reproduce this is by providing a wrong path to Page#load. Try dropping the "../" at the beginning; your tests are most likely running from your project's root.
